### ISSUE TITLE
Garbled texts and break link in PowerShell Module Browser

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/windows-powershell-docs#1100]
**Submitted to [site feedback issue #1574](https://github.com/MicrosoftDocs/feedback/issues/1574) by @ToMakeSense on 6/1**

Link to article:
A few garbled texts in below three links:

Windows 10 and Windows Server 2016 PowerShell Module Reference
Windows 8.1 and Windows Server 2012 R2 PowerShell Module Reference
Windows 8 and Windows Server 2012 PowerShell Module Reference
Break link in Azure Service Management PowerShell Module Reference

Problem:
Totally three garbled texts(�) each can be found in adrms Module section and grouppolicy Module section in the first three links.

Break link can be find for Azure(https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0) Module, the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

**Comment by nschonni** [comment]
The garbled text part will be resolved with #1084

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@ryanmajidi The referenced PR is being rolled into review. Thank you for your feedback.

@nschonni  Thank you for your contribution.

**Comment by e0i** [comment]
@nschonni The issue has been addressed with the help of your contribution as the PR #1084 has been merged.

Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by nschonni** [comment]
> Break link can be find for Azure(https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0) Module, the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

Think this is still an issue, but could probably be moved to a new one

**Comment by mairaw** [comment]
There were also questions about when the changes are going live on the original issue @e0i. Any ETA on that?

**Comment by ToMakeSense** [comment]
@nschonni @e0i @ryanmajidi  @mairaw the “garbled texts” issue is fixed and documentation is updated, but the "Break link" isn't. It's better to get it referenced, even Azure module(ASM) is out of date and hardly used any more, 

Break link in [Azure Service Management PowerShell Module Reference ](https://docs.microsoft.com/en-us/powershell/module/?view=azuresmps-4.0.0)
![image](https://user-images.githubusercontent.com/6244148/75016094-31433500-54c5-11ea-8e5b-cb2335d3b496.png)

Break link can be find for **`Azure`** Module (https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0), the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

**Comment by e0i** [comment]
> @nschonni @e0i @ryanmajidi @mairaw the “garbled texts” issue is fixed and documentation is updated, but the "Break link" isn't. It's better to get it referenced, even Azure module(ASM) is out of date and hardly used any more,
> 
> Break link in [Azure Service Management PowerShell Module Reference ](https://docs.microsoft.com/en-us/powershell/module/?view=azuresmps-4.0.0)
> ![image](https://user-images.githubusercontent.com/6244148/75016094-31433500-54c5-11ea-8e5b-cb2335d3b496.png)
> 
> Break link can be find for **`Azure`** Module (https://docs.microsoft.com/en-us/powershell/module/Azure/?view=azuresmps-4.0.0), the actual URL is: https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/overview?view=azuresmps-4.0.0

@ToMakeSense Thank you for spotting this. The document will be revised by an independent contributor soon.

**Comment by e0i** [comment]
@ToMakeSense Apologies, It has been found that the source for "break links" is not located within this repository.

A better channel to submit feedback for that issue would be through [Microsoft Docs Feedback](https://github.com/MicrosoftDocs/feedback/issues).

Thank you.
