### ISSUE TITLE
Example PowerShell Code provide to confirm which certificate is being used is incorrect

### ISSUE THREAD

**Issue by plydet** [MicrosoftDocs/windows-powershell-docs#3187]
Correct Code:
$CertInBase64 = New-AdfsAzureMfaTenantCertificate -TenantID $TenantID
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]([System.Convert]::FromBase64String($CertInBase64))
$cert | Format-List *

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 662933f4-b5a8-6171-8e58-c4fbee11f314
* Version Independent ID: cfefffa6-78f0-124b-d91d-95f0bbecfa98
* Content: [New-AdfsAzureMfaTenantCertificate (ADFS)](https://learn.microsoft.com/en-us/powershell/module/adfs/new-adfsazuremfatenantcertificate?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/adfs/New-AdfsAzureMfaTenantCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/adfs/New-AdfsAzureMfaTenantCertificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by msbemba** [comment]
@plydet Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/windows-powershell-docs/pull/3476

Once the author approves, the changes will eb livel

Thanks
Sri

**Comment by plydet** [comment]
the code uploaded is still incorrect, below is what needs to be uploaded
`$CertInBase64 = New-AdfsAzureMfaTenantCertificate -TenantID $TenantID # if a certificate already exists' you will get a warning and it will not generate a new certificate.
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]([System.Convert]::FromBase64String($CertInBase64))
$cert | Format-List *`

**Comment by msbemba** [comment]
@plydet  We have made the changes to the document.

This will be live shortly.

Thanks
Sri

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by plydet** [comment]
Official

The code you have upload is still incorrect.. please refer to comments on May 22 2023, your site is truncating the required code or you're not formatting it correctly...

$CertInBase64 = New-AdfsAzureMfaTenantCertificate -TenantID $TenantID # if a certificate already exists' you will get a warning and it will not generate a new certificate.
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]([System.Convert]::FromBase64String($CertInBase64))
$cert | Format-List *

**Comment by scanum** [comment]
@msbemba

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
