### ISSUE TITLE
Page is not being updated

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-powershell-docs#983]
Hello. As of today, 14 April 2019, the ["Repair-Volume (`win10-ps`)", page on Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/storage/repair-volume?view=win10-ps) is not reflecting changes made to its GitHub source code as far back as 15 January 2019. 

The same complaint applies to the [`winserver2012-ps` version of the "Repair-Volume" page](https://docs.microsoft.com/en-us/powershell/module/storage/repair-volume?view=winserver2012-ps), i.e. it also is not reflecting changes as far back as 15 January 2019.

Come on, now, Microsoft! Our workflow depends on these pages. Could you please, please, please update the Docs?

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b81a5e26-f7ff-fc15-813d-f8baf8e0dc40
* Version Independent ID: e691576d-fcfb-2200-775b-504da087c6f8
* Content: [Repair-Volume (storage)](https://docs.microsoft.com/en-us/powershell/module/storage/repair-volume?view=win10-ps)
* Content Source: [docset/windows/storage/repair-volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storage/repair-volume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Under investigation.

**Comment by e0i** [comment]
@skycommand The deployment system has been fixed and public contributions via GitHub are now being continuously synced to live. Thank you for providing feedback.

**Comment by skycommand** [comment]
@e0i Hi. I can confirm that docs.microsoft.com has been updated. But... Windows clients are still not receiving these changes. In other words, `Get-Help Repair-Volume` still returns outdated info, even after I tried `Update-Help`. In fact, nowadays, Update-Help generates more error messages than ever.

```plaintext
Failed to update Help for the module(s) 'AppvClient, AppvSequencer, AutoSequencer, Defender, HgsClient, HgsDiagnostics, HostComputeService, HostNetworkingService, Microsoft.PowerShell.ODataUtils, Microsoft.PowerShell.Operation.Validation, UEV, Whea, WindowsDeveloperLicense' with UI culture(s) {en-US} : Unable to connect to Help content. The server on which Help content is stored might not be available. Verify that the server is available, or wait until the server is back online, and then try the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand

Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property in the module manifest is valid or check your network connection and then try the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand
````
